workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 120
    instance_type: linux   # Free plan compatible

    environment:
      java: 17
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
