import CookieManager from '@react-native-cookies/cookies';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { YtDlpNative } from '../native/YtDlpModule';

export class CookieManagerService {
    /** Map of platform name -> canonical domain URL for CookieManager calls */
    private static readonly PLATFORM_URLS: Record<string, string> = {
        instagram: 'https://www.instagram.com',
        facebook: 'https://www.facebook.com',
    };

    static async getCookiesForPlatform(platform: string): Promise<string | null> {
        try {
            const key = platform.toLowerCase();
            const expiry = await AsyncStorage.getItem(`cookies_expiry_${key}`);
            if (expiry && Date.now() > parseInt(expiry, 10)) {
                // Cookies expired — remove only AsyncStorage keys (not WebView cookies)
                // Avoid calling CookieManager with a non-URL string which throws an error
                await AsyncStorage.removeItem(`cookies_path_${key}`);
                await AsyncStorage.removeItem(`cookies_expiry_${key}`);
                return null;
            }

            const storedPath = await AsyncStorage.getItem(`cookies_path_${key}`);
            if (storedPath) {
                return storedPath;
            }
            return null;
        } catch (error) {
            console.warn('Error reading cookie path for', platform, ':', error);
            return null;
        }
    }

    static async extractAndSaveCookies(platform: string, url: string): Promise<boolean> {
        try {
            // Get all cookies for the platform URL
            const cookies = await CookieManager.get(url, true); // true for useWebKit
            
            if (!cookies || Object.keys(cookies).length === 0) {
                return false;
            }

            // Convert to Netscape format required by yt-dlp
            // Format: domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
            let netscapeTxt = `# Netscape HTTP Cookie File\n# This file is generated by VibeDownloader\n\n`;
            
            let domain = '';
            try {
                const urlObj = new URL(url) as any;
                domain = '.' + urlObj.hostname.replace('www.', '');
            } catch (e) {
                // Natively fallback if URL is malformed
                domain = platform.toLowerCase().includes('insta') ? '.instagram.com' : '.facebook.com';
            }
            
            let hasSession = false;
            let minExpiry = 1893456000; // 2030

            Object.values(cookies).forEach((cookie) => {
                const isSecure = true; // Most social media uses secure cookies
                const includeSubdomains = true;
                const path = cookie.path || '/';
                const secureStr = isSecure ? 'TRUE' : 'FALSE';
                const subStr = includeSubdomains ? 'TRUE' : 'FALSE';
                // Use year 2030 for expiry if none provided
                const expiry = cookie.expires ? Math.floor(new Date(cookie.expires).getTime() / 1000) : 1893456000;
                
                if (cookie.expires) {
                    const expiryMs = new Date(cookie.expires).getTime();
                    if (expiryMs < minExpiry * 1000) minExpiry = expiryMs / 1000;
                }

                netscapeTxt += `${domain}\t${subStr}\t${path}\t${secureStr}\t${expiry}\t${cookie.name}\t${cookie.value}\n`;

                if (cookie.name === 'sessionid' || cookie.name === 'c_user') {
                    hasSession = true;
                }
            });

            // If we didn't find the critical session cookie, don't save it.
            // Some platforms don't strictly use sessionid, so we skip this strict check for non-meta platforms
            if (!hasSession && ['instagram', 'facebook'].includes(platform.toLowerCase())) {
                return false;
            }

            // Save to file via native module to bypass need for react-native-fs
            const filePath = await YtDlpNative.saveCookiesToFile(netscapeTxt, platform.toLowerCase());
            
            // Link path in AsyncStorage
            await AsyncStorage.setItem(`cookies_path_${platform.toLowerCase()}`, filePath);
            
            // 7 days default fallback if not parsed
            let finalExpiryMs = minExpiry === 1893456000 ? Date.now() + (7 * 24 * 60 * 60 * 1000) : (minExpiry * 1000);
            await AsyncStorage.setItem(`cookies_expiry_${platform.toLowerCase()}`, finalExpiryMs.toString());
            
            return true;
        } catch (error) {
            console.error('Cookie extraction failed:', error);
            return false;
        }
    }

    static async clearCookies(platform: string, url?: string) {
        const key = platform.toLowerCase();
        // Resolve a proper URL to pass to CookieManager; fall back to stored map.
        const resolvedUrl = url && url.startsWith('http')
            ? url
            : (this.PLATFORM_URLS[key] ?? null);

        try {
            if (resolvedUrl) {
                await CookieManager.clearByName(resolvedUrl, 'sessionid');
                await CookieManager.clearByName(resolvedUrl, 'c_user');
            }
        } catch (e) {
            console.warn('CookieManager.clearByName failed (non-critical):', e);
        }

        try {
            await AsyncStorage.removeItem(`cookies_path_${key}`);
            await AsyncStorage.removeItem(`cookies_expiry_${key}`);
        } catch (e) {
            console.error('Failed to clear AsyncStorage cookie data:', e);
        }
    }
}
