import { NativeModules, NativeEventEmitter } from 'react-native';

// Type definitions for VideoInfo
export interface Format {
    formatId: string;
    formatNote?: string;
    ext?: string;
    filesize?: number;
    tbr?: number;
    width?: number;
    height?: number;
    resolution?: string;
    fps?: number;
    vcodec?: string;
    acodec?: string;
    hasVideo?: boolean;
    hasAudio?: boolean;
}

/**
 * One caption track published by the source.
 *
 * A language can be published twice - once uploaded by the author and once
 * generated by the platform - and those are genuinely different files, so the
 * language code alone is not a usable identity.
 */
export interface SubtitleTrack {
    key: string;
    /** yt-dlp language code, passed through to the subtitle download verbatim. */
    lang: string;
    /** Display label, e.g. "English" or "English (auto)". */
    label: string;
    /** Language name on its own, e.g. "English". */
    langLabel: string;
    /** True for platform-generated captions, false for author-uploaded ones. */
    isAuto: boolean;
    /** Subtitle formats the source actually offers for this track. */
    formats: string[];
}

/**
 * One audio language. Only present when the source publishes more than one,
 * which is what keeps the picker hidden for single-language media.
 */
export interface AudioTrack {
    key: string;
    /** yt-dlp language code, e.g. "en-US", "bn", "hi". */
    lang: string;
    langLabel: string;
    /** True for the language the video was recorded in. */
    isOriginal: boolean;
    /** yt-dlp format id to download, e.g. "140-1". */
    formatId: string;
    ext: string;
    /** Audio codec, e.g. "mp4a.40.2". */
    acodec: string;
    /** Approximate bitrate in kbps, 0 when the source does not report one. */
    abr: number;
}

export interface VideoInfo {
    id: string;
    title: string;
    description: string;
    thumbnail: string;
    uploader: string;
    uploaderUrl: string;
    duration: number; // seconds
    viewCount: number;
    likeCount: number;
    uploadDate: string;
    extractor: string; // youtube, instagram, etc
    url: string;
    platform: string;
    formats: Format[];
    /** Caption tracks, empty when the source publishes none. */
    subtitles?: SubtitleTrack[];
    /** Per-language audio tracks, empty unless the source is dubbed. */
    audioTracks?: AudioTrack[];
    ext?: string;
    filesize?: number;
    width?: number;
    height?: number;
    fps?: number;
    /**
     * True while only the fast oEmbed fields are known. Formats, subtitles and
     * audio tracks are still loading, so download controls must stay hidden.
     */
    partial?: boolean;
    artist?: string;
    track?: string;
    isMusic?: boolean;
    categories?: string[];
}

/** Cheap subset available before the full extraction finishes. */
export interface QuickInfo {
    platform: string;
    title: string;
    uploader: string;
    thumbnail: string;
}

/** Where a caption or lyrics file ended up after being published to storage. */
export interface SavedFileResult {
    filePath: string;
    fileName: string;
}

export interface ValidationResult {
    valid: boolean;
    platform: string | null;
}

export interface DownloadProgress {
    processId: string;
    progress: number;
    eta: number;
    line: string;
}

export interface DownloadResult {
    processId: string;
    outputDir: string;
    exitCode: number;
    output: string;
}

export interface DownloadedFile {
    name: string;
    path: string;
    size: number;
    modified: number;
    platform: string;
    contentType: string;
    extension: string;
    thumbnail?: string | null;
}

// Shared Data from Intent
export interface SharedData {
    url: string;
    platform: string | null;
    autoFetch: boolean;
}

// Native Module Interface
export interface YtDlpNativeModule {
    fetchInfo(url: string, options?: { cookies?: string; args?: string[] }): Promise<VideoInfo>;
    /**
     * Title/uploader/thumbnail from oEmbed in a single request. Resolves with
     * `null` for platforms without an oEmbed endpoint. Lets the details screen
     * render while the full extraction is still running.
     */
    fetchQuickInfo(url: string): Promise<QuickInfo | null>;
  /**
   * Whether yt-dlp postprocessing (MP3/WAV conversion, DASH muxing) can run.
   * False on devices whose page size the bundled ffmpeg does not support.
   */
  isFfmpegAvailable(): Promise<boolean>;
  /** Reads a UTF-8 text file (lyrics/subtitles) for the in-app viewer. */
  readTextFile(filePath: string): Promise<string>;
    download(url: string, formatId: string | null, processId: string, options?: { title?: string; artist?: string; platform?: string; cookies?: string; thumbnailPath?: string; audioFormatId?: string }): Promise<DownloadResult>;
    /**
     * Downloads one caption track and publishes it to
     * Download/VibeDownloader/<Platform>/Subtitles.
     *
     * Rejects with a user-readable message when the language publishes no
     * captions, so the picker can show it verbatim.
     */
    downloadSubtitles(url: string, options: { lang: string; isAuto: boolean; format?: 'srt' | 'vtt'; platform?: string; cookies?: string; title?: string }): Promise<SavedFileResult>;
    /** Writes a lyrics export to Download/VibeDownloader/Lyrics. */
    saveLyricsFile(fileName: string, content: string, platform?: string | null): Promise<SavedFileResult>;
    downloadSpotifyTrack(searchQuery: string, title: string, artist: string, album: string, thumbnail: string | null, processId: string): Promise<DownloadResult>;
    cancelDownload(processId: string): Promise<boolean>;
    updateYtDlp(): Promise<{ status: string }>;
    getVersions(): Promise<{ appVersion: string; ytdlpVersion: string }>;
    getSupportedPlatforms(): Promise<string[]>;
    validateUrl(url: string): Promise<ValidationResult>;
    getOutputDirectory(): Promise<string>;
    getPlaylistInfo(url: string, options?: { cookies?: string; extractorArgs?: string; args?: string[] }): Promise<string>;
    listDownloadedFiles(): Promise<DownloadedFile[]>;
    deleteFile(filePath: string): Promise<boolean>;
    openFile(filePath: string): Promise<boolean>;
    shareFile(filePath: string): Promise<boolean>;
    // Share Intent Methods
    getSharedText(): Promise<string | null>;
    getSharedData(): Promise<SharedData | null>;
    getClipboardText(): Promise<string>;
    saveThumbnail(url: string, title: string): Promise<string>;
    saveCookiesToFile(cookiesText: string, platform: string): Promise<string>;
    getCookiesFilePath(platform: string): Promise<string | null>;
    fileExists(path: string): Promise<boolean>;
    /**
     * Deletes the cookie .txt file at [path] from the native filesDir.
     * Use this on logout to ensure stale session tokens don't persist across
     * app reinstalls or debug builds.
     */
    deleteCookieFile(path: string): Promise<boolean>;
    /**
     * Reads ALL cookies for [url] directly from Android's WebView CookieManager,
     * including HttpOnly session cookies that JS / @react-native-cookies cannot see.
     * Returns a flat string like "name1=value1; name2=value2" or "" if none found.
     */
    getWebViewCookies(url: string): Promise<string>;
    /**
     * Downloads [url] to the app's thumbnail cache directory and returns
     * the absolute local path. Pass this path to download() as thumbnailPath
     * so yt-dlp embeds the high-res album art instead of the video thumbnail.
     */
    downloadThumbnailToCache(url: string): Promise<string>;
}

const { YtDlpModule } = NativeModules;

export const YtDlpNative: YtDlpNativeModule = YtDlpModule;

export const ytDlpEventEmitter = new NativeEventEmitter(YtDlpModule);

export function onDownloadProgress(callback: (progress: DownloadProgress) => void): () => void {
    const subscription = ytDlpEventEmitter.addListener('onDownloadProgress', callback);
    return () => subscription.remove();
}

export declare type VideoFormat = Format;

// Helpers
export const formatDuration = (seconds: number): string => {
    if (!seconds) return '0:00';
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);

    if (h > 0) {
        return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    }
    return `${m}:${s.toString().padStart(2, '0')}`;
};

export const formatFileSize = (bytes: number): string => {
    if (!bytes) return 'N/A';
    const units = ['B', 'KB', 'MB', 'GB'];
    let size = bytes;
    let unitIndex = 0;

    while (size >= 1024 && unitIndex < units.length - 1) {
        size /= 1024;
        unitIndex++;
    }

    return `${size.toFixed(1)} ${units[unitIndex]}`;
};

export const formatViewCount = (count: number): string => {
    if (!count) return '0';
    if (count >= 1000000) return `${(count / 1000000).toFixed(1)}M`;
    if (count >= 1000) return `${(count / 1000).toFixed(1)}K`;
    return count.toString();
};
